- hosts: localhost
  connection: local
  become: true
  tasks:
  # Task 1: install nginx
  - name: install nginx
    apt:
      name: nginx
      state: present
      update_cache: true  
      # make the install fail if the update cache time is bigger than 1.

  # Task 2: copy our nginx.conf file to the relevant place
  - name: Copy nginx file over
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    register: nginx_config
    failed_when: nginx_config.diff.after.path == nginx_config.diff.before.path
  # Task 3: restart nginx to take in the new changes
  - name: Restart nginx if needed
    service:
      name: nginx
      state: restarted
    when: nginx_config.changed == true
  # Task 4: show the information from the copy task (task 2 + 3)
  - name: Display information from the copy task
    debug: 
      msg: "{{ nginx_config }}"
