- hosts: localhost
  connection: local
  become: true
  tasks:
  # Task 1: install nginx
  - name: install nginx
    apt:
      name: nginx
      state: present
      update_cache: true
  # Task 2: copy our nginx.conf file to the relevant place
  - name: Copy nginx file over
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    register: nginx_config
  # Task 3: restart nginx to take in the new changes
  - name: Restart nginx if needed
    service:
      name: nginx
      state: restarted
    when: nginx_config.changed == true