# a playbook used to uninstall nginx
- hosts: localhost
  connection: local
  become: true
  tasks:
  # Task 1: uninstall nginx
  - name: uninstall nginx
    apt:
      name: nginx
      state: absent
      update_cache: true  
  # Task 2: stop nginx services
  - name: "Stop Nginx Services"
    service:
      name: nginx
      state: stopped
  # Task 3: uninstall packages 
  - name: "Uninstall packages"
    apt:
      name: nginx
      state: absent
      autoremove: yes