# Exercise: Create a playbook that takes the IP of your host and creates a file containing that IP

- hosts: localhost
  connection: local
  become: true
  tasks:
  # Task 1: Get the host IP address
  - name: Print hostvars
    debug: 
      msg: "{{ hostvars }}" 
    