# Exercise: Create a playbook that takes the IP of your host and creates a file containing that IP

- hosts: localhost
  connection: local
  become: true
  vars:
    ip_address: "{{ ansible_default_ipv4.address }}"
  tasks:
  # Task 1: Create an empty file
  - name: Create an empty file
    copy:
      dest: "/home/file.txt"
      content: |
        {{ip_address}}